# teams.py

players = {
    "Sachin Tendulkar": {
        "country": "India",
        "role": "batsman",
        "batting_avg": 55,
        "attack": 85,
        "defense": 95,
        "bowling_avg": None,
        "bowling_skill": 0,
    },
    "Ricky Ponting": {
        "country": "Australia",
        "role": "batsman",
        "batting_avg": 58,
        "attack": 90,
        "defense": 88,
        "bowling_avg": None,
        "bowling_skill": 0,
    },
    "Brian Lara": {
        "country": "West Indies",
        "role": "batsman",
        "batting_avg": 53,
        "attack": 92,
        "defense": 85,
        "bowling_avg": None,
        "bowling_skill": 0,
    },
    "Rahul Dravid": {
        "country": "India",
        "role": "batsman",
        "batting_avg": 52,
        "attack": 65,
        "defense": 98,
        "bowling_avg": None,
        "bowling_skill": 0,
    },
    "Virender Sehwag": {
        "country": "India",
        "role": "batsman",
        "batting_avg": 50,
        "attack": 98,
        "defense": 60,
        "bowling_avg": None,
        "bowling_skill": 20,
    },
    "Kumar Sangakkara": {
        "country": "Sri Lanka",
        "role": "batsman",
        "batting_avg": 57,
        "attack": 80,
        "defense": 90,
        "bowling_avg": None,
        "bowling_skill": 0,
    },
    "Jacques Kallis": {
        "country": "South Africa",
        "role": "allrounder",
        "batting_avg": 55,
        "attack": 78,
        "defense": 88,
        "bowling_avg": 32,
        "bowling_skill": 70,
    },
    "Sourav Ganguly": {
        "country": "India",
        "role": "batsman",
        "batting_avg": 42,
        "attack": 80,
        "defense": 75,
        "bowling_avg": None,
        "bowling_skill": 30,
    },
    "Shane Warne": {
        "country": "Australia",
        "role": "bowler",
        "batting_avg": 17,
        "attack": 40,
        "defense": 30,
        "bowling_avg": 25,
        "bowling_skill": 98,
    },
    "Muttiah Muralitharan": {
        "country": "Sri Lanka",
        "role": "bowler",
        "batting_avg": 12,
        "attack": 20,
        "defense": 20,
        "bowling_avg": 22,
        "bowling_skill": 97,
    },
    "Glenn McGrath": {
        "country": "Australia",
        "role": "bowler",
        "batting_avg": 8,
        "attack": 15,
        "defense": 20,
        "bowling_avg": 21,
        "bowling_skill": 93,
    },
    "Anil Kumble": {
        "country": "India",
        "role": "bowler",
        "batting_avg": 18,
        "attack": 25,
        "defense": 25,
        "bowling_avg": 29,
        "bowling_skill": 88,
    },
    "Harbhajan Singh": {
        "country": "India",
        "role": "bowler",
        "batting_avg": 20,
        "attack": 35,
        "defense": 28,
        "bowling_avg": 32,
        "bowling_skill": 82,
    },
    "Brett Lee": {
        "country": "Australia",
        "role": "bowler",
        "batting_avg": 20,
        "attack": 35,
        "defense": 25,
        "bowling_avg": 30,
        "bowling_skill": 85,
    },
    "Adam Gilchrist": {
        "country": "Australia",
        "role": "wicketkeeper",
        "batting_avg": 47,
        "attack": 92,
        "defense": 70,
        "bowling_avg": None,
        "bowling_skill": 0,
    },
    "MS Dhoni": {
        "country": "India",
        "role": "wicketkeeper",
        "batting_avg": 38,
        "attack": 82,
        "defense": 78,
        "bowling_avg": None,
        "bowling_skill": 0,
    },
    "Andrew Flintoff": {
        "country": "England",
        "role": "allrounder",
        "batting_avg": 32,
        "attack": 80,
        "defense": 65,
        "bowling_avg": 33,
        "bowling_skill": 75,
    },
    "VVS Laxman": {
        "country": "India",
        "role": "batsman",
        "batting_avg": 45,
        "attack": 72,
        "defense": 88,
        "bowling_avg": None,
        "bowling_skill": 0,
    },
}
